# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='author')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('urlToImage', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='url to the image')),
                ('publishedAt', models.DateTimeField(verbose_name='published at')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['-publishedAt'],
                'verbose_name_plural': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('newsapi_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='newsapi id')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'source',
                'ordering': ['name'],
                'verbose_name_plural': 'sources',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Source'),
        ),
    ]
